### ISSUE TITLE
reimplement serialize as serializeBinary & serializeBinaryToWriter

### ISSUE THREAD

**Issue by marcushultman** [thesayyn/protoc-gen-ts#13]
- `serialize` does not exist on `Message` but is implemented similarly to how the static `serializeBinaryToWriter` should be implemented. Removing is a breaking change.
- `serializeBinary` is not implemented/generated but a proper `abstract` method on `Message` (adding throwing stub in https://github.com/thesayyn/protoc-gen-ts/pull/12)

**Comment by thesayyn** [comment]
I'm kind of a freak who would like to tidy up things so that why I have done something like this. Probably you understand it already but let me clarify what I have with those methods.
I have managed to put all serializing and deserializing stuff into those two methods. 
I had done this because having four methods doing the different part of the serializing and deserializing work seemed kinda confusing from the user perspective.
Besides theese two methods are only used internally by other message types. 
But yeah when it comes to backward compatibility this change led to a breaking change which is not so important in my opinion cause literally you can just rename everything in your codebase and you are good to go.

**Comment by thesayyn** [comment]
Also, these changes have some interopability issues with @types/google-protobuf. When I realized this it was too late cause I was almost done writing the plugin. 
May be we can send a PR to make those methods optional?

**Comment by jackpunt** [comment]
I'll vote for following the interface from google-protobuf.

My current problem is that the deserialize method is static to the specific Message class.

Previously, I could pass my web-socket handler a (msg_class: typeof jspb.Message) 
and find the deserializer from that 'class' object. msg_class.deserialize(data)
But jspb.Message does not have a ".serialize" 
(and the websocket parser does not want to hard code the message class/static)
I can work around using: msg_class['serialize'](data) but then eslint complains...

Hopefully not related: 
 When AMessage.serialize(data) is ultimately called, it fails due to:  (data instanceof Uint8Array)
 not recognizing my ArrayBuffer as being a Uint8Array; so:
 const reader =  (data instanceof Uint8Array) ? ... : bytes;

Workaround: hand edit MyProto.ts/js to use (data instanceof ArrayBuffer)
Im using:     "ws": "^7.4.4"

**Comment by thesayyn** [comment]
One option would be that we implement these methods and make the forward the call to serialize and deserialize to have a backward-compatible solution.

**Comment by jackpunt** [comment]
I'm all in favor of backward and standard compatibilty.

As for (bytes instanceof Uint8Array), i'll advocate for reversing the test:
        let reader = (bytes instanceof pb_1.BinaryReader) ? bytes : new pb_1.BinaryReader(bytes), message = new AMessage();

That way there are fewer prototypes to confuse javascript...

**Comment by thesayyn** [comment]
that makes sense. this way we wouldn’t have to add an additional OR expression for everything. 
I'll send a pr for this

**Comment by jackpunt** [comment]
FWIW, I am making progress using these "scripts" on the 0.3.5 generated *Proto.ts files::
```
    "patch-serial": "replace 'serializeBinary(): Uint8Array { throw new Error(\"Method not implemented.\"); }' 'serializeBinary(): Uint8Array { return this.serialize(); }' -- *Proto.ts",
    "patch-return": "replace 'return writer.getResultBuffer();' 'return writer.getResultBuffer();\n        return undefined;' -- *Proto.ts",
    "patch-reader": "replace -s 'Uint8Array ? new pb_1.BinaryReader(bytes) : bytes' 'pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes)' --  *Proto.ts",
```

**Comment by thesayyn** [comment]
Hey jack. In alpha branch i have implemented a new feature that puts 'serializeBinary' and 'deserializeBinary' methods which in turn delegates themselves to "serialize" and "deserialize" respectively. Would that work for you?

**Comment by jackpunt** [comment]
Yes, that would obviate the patch-serial script.
(I made the patch to update the API in anticipation of your new release)

**Comment by thesayyn** [comment]
@jackpunt a PR has landed for this. Will you be able to review and give insights on if there is room for improvements?

**Comment by jackpunt** [comment]
I'll give it a try; what is the appropriate incantation that I should use to get the updated version?

**Comment by thesayyn** [comment]
> I'll give it a try; what is the appropriate incantation that I should use to get the updated version?

I'll release it today.

**Comment by thesayyn** [comment]
this has been released with version: v0.3.6-rc1 let me know if it works for you.

**Comment by jackpunt** [comment]
neither -rc1, nor -rc2 working for me...

````
:wspbclient>npm install protoc-gen-ts@0.3.6-rc2 -g

added 2 packages, changed 1 package, and audited 4 packages in 1s

found 0 vulnerabilities
:wspbclient>npm ls -g google-protobuf
/Users/jpeck/.nvm/versions/node/v15.14.0/lib
├── google-protobuf@3.15.8
└─┬ protoc-gen-ts@0.3.6-rc2
  └── google-protobuf@3.15.8 deduped
:wspbclient>protoc --version
libprotoc 3.15.8
:wspbclient>npm run protots

> wspbclient@1.2.8 protots
> protoc -I src/proto --ts_out=src src/proto/*.proto

/Users/jpeck/.nvm/versions/node/v15.14.0/bin/protoc-gen-ts: line 1: syntax error near unexpected token `('
/Users/jpeck/.nvm/versions/node/v15.14.0/bin/protoc-gen-ts: line 1: `const plugin = require("./compiler/plugin");'
--ts_out: protoc-gen-ts: Plugin failed with status code 2.
````

**Comment by thesayyn** [comment]
Ah, that is something I can reproduce. Turns out to be a chmod issue of the binary file.

**Comment by thesayyn** [comment]
@jackpunt Could you try with 0.3.6-rc3?

**Comment by jackpunt** [comment]
It works! (installs, protoc runs, code looks good, tests pass)
Have not recoded to use 'deserializeBinary' but good to have it there for compatibility.

**Comment by jackpunt** [comment]
Hmm, I discover that a message with a 'repeated' field now comes as *required* rather than *optional*
(generated code missing the '?' in constructor signature)

**Comment by thesayyn** [comment]
@jackpunt that is not supposed to do that right? if not can you create another issue so that I can fix it as well?

**Comment by jackpunt** [comment]
LGTM, thx!
