### ISSUE TITLE
Maps support

### ISSUE THREAD

**Issue by Monahawk** [thesayyn/protoc-gen-ts#14]
Hi,

atm, I have an issue with working with map types in the typescript generated messages.

In my Proto files, I use map<key, value> type.

In the .AsObject also it appears as Array<[key, value]>. And in the main jspb.Message type, there is only a getter and a clear method for it.

Any way to work around it?

**Comment by thesayyn** [comment]
Hi @Monahawk. 

Currently, maps are not supported since it requires significant work to do implement. That said, `map<type, type>` is in fact serialized/deserialized as an array in protocol buffer format which means `maps` are 'arrays' in protocol buffers wire format.
Hence, they appear as arrays if you are compiling the protos via this plugin because the plugin does not perform any operation on them.

I believe you can use the built-in `Map` class in javascript to work around this issue until me/anyone adds support for maps.

The workaround would look like below;

```typescript
const fieldMap = new Map(message.repeated_field);
```
Also, a PR to support this is appreciated.

**Comment by thesayyn** [comment]
Update on this issue

this is on top of my backlog.
