### ISSUE TITLE
Hint how to use with grpc-web?

### ISSUE THREAD

**Issue by blake-regalia** [thesayyn/protoc-gen-ts#152]
I understand that there is ongoing refactoring to support grpc-web without manual intervention, and I've dived thru the various issues/discussions, but i'm not super familiar with the various components.

Are there any references that could be provided to help devs in my situation get started? Plugging `grpc-web` into `--ts_opt=grpc_package=xxx` option doesn't work and i'm sure there's more to it than that, but no idea where to start. Any help would be greatly appreciated.

**Comment by thesayyn** [comment]
current workaround is;

1- use protoc-gen-ts to generate  `@grpc/grpc-js` compatible RPC code and put it behind an envoy proxy so that grpc-web can talk to it.
2- use protoc-gen-ts to generate `message`, `enums` etc.
3- use grpc-web generator to generate grpc-web compatible client code and replace imports. `xxxx_pb` to `xxxx`

there might be additional steps and code paths to update to make it work with protoc-gen-ts but the obvious ones are above.

Happy to guide anyone who's up for making an example.

**Comment by thesayyn** [comment]
#102 landed. I'll cut a new release shortly.
