### ISSUE TITLE
fromObject(toObject()) is not working correctly for oneof fields

### ISSUE THREAD

**Issue by Guitar1st** [thesayyn/protoc-gen-ts#209]
0.8.4 works fine
0.8.6 doesn't work
Eg if I have this proto message:

message LimitValue {
  oneof value {
    int64 int_value = 1;
    double double_value = 2;
  }
}

Compile it and try to do `LimitValue.fromObject(new LimitValue({int_value: 123}).toObject())` it will return me `{int_value: 0, double_value: 0}`
On the other hand:
`LimitValue.fromObject(new LimitValue({double_value: 123}).toObject())` it will return `{int_value: 0, double_value: 123}` (so this case works fine)
The problem is that toObject sets all the possible oneof values to 0 and fromObject doesn't know which one is correct
Probably toObject method should use the `has_{field_name}` rather than != null

**Comment by roysandrew** [comment]
+1 it looks like the 'return defaults' in toObject will always add every field defined as 'oneof', as a result if you try to quickly clone an instance of a message with:

`Message.fromObject(messageOld.toObject())`

you'll drop the contents of the oneof fields, and only keep the one numerically last in the proto spec.

I think a reasonable fix is that instead of this condition:
https://github.com/thesayyn/protoc-gen-ts/blob/863fed9eceb5ffe46f8575591207c7c1583d34ed/src/descriptor.ts#L443

We need to lookup the current result of computeOneofCase and include that with default in toObject.

**Comment by thesayyn** [comment]
This is fixed with the rust rewrite. Now we conform to protobuf json encoding.
