### ISSUE TITLE
Message with repeated custom type generating incorrect key name in AsObject/toObject()

### ISSUE THREAD

**Issue by arvinsingla** [thesayyn/protoc-gen-ts#26]
I'm pretty new to Protobuf but have come across something odd in a current project. Given this proto file:

```
syntax = "proto3";

package technician.api.v1;

message Technician {
  // The id for the contractor.
  optional int32 id = 1;
  // The technician_ref for the contractor.
  optional string technician_ref = 2;
  // The oem_ref for the contractor.
  optional string oem_ref = 3;
}

service TechnicianAPI {
  // Return a list of 0 or more technicians for the given request.
  rpc ListTechnicians(ListTechniciansRequest) returns (ListTechniciansResponse);
}

// A response containing a list of technicians.
message ListTechniciansResponse {
  repeated Technician technicians = 1;
}

// A request to list technicians.
message ListTechniciansRequest {
  // The technician_ref to start listing from. If not provided, start from the beginning.
  string start_technician_ref = 1;
  // The maximum number of results to return, default to 100
  uint32 count = 2;
}
```

When the typescript is generated the `ListTechnicianResponse` looks like this.

```
export namespace ListTechniciansResponse {
    export type AsObject = {
        techniciansList: Array<technician_api_v1_technician_pb.Technician.AsObject>,
    }
}
```

The key `technicians` is now suffixed with `List` which doesn't match the protobuf and as such doesn't result in the correct output when returned. Again I'm new to protobuf so if this is expected behaviour please let me know but this doesn't seem correct to me and I don't see anything about it in any documentation.

**Comment by thesayyn** [comment]
Hey there, that's okay I would like to assist you anyway. 

So my first impression on your issue is that I think you understood this plugin wrong. Because this plugin does not put a suffix to the end of the property names. So there's a high possibility that you are mixing this plugin with another plugin which only generates typescript declarations. So I would recommend you to check the bottom of the readme file. 

To solve your issue, you only need to use this plugin and nothing else. Like so 

`protoc  - - ts_out=. /outputdir`

**Comment by arvinsingla** [comment]
Thank you for the response. You are correct that I didn't understand the plugin correctly. Upon further digging into our build process I realize this is an issue much higher up. https://github.com/protocolbuffers/protobuf/issues/4518
