### ISSUE TITLE
哥们额，多来点文档

### ISSUE THREAD

**Issue by GeTOUO** [thesayyn/protoc-gen-ts#3]
详细介绍一下生成的范围和目前使用有没有什么问题呢？最好带一点骚气的示例。
支持类似于这样的操作吗？
```
class ProtoCoder {
    decode<T extends Message>(bytes: Unit8Arrays, clz: new(): T): T
}

than:

const m1: Person  = decode(bytes, Person)
const m2: People  = decode(bytes, People)
```

**Comment by thesayyn** [comment]
I couldn't understand the question but from what you wrote I think you want to be able to create proto messages through an helper function. But this plugin does not generate any generic helper function to create proto messages. Instead, it generates a method in every single proto  message. The method called as deserialize (similar to decode) and you can pass your unit8array to deserialize method in the particular message and could get the constructed (filled) message.

All you need to do is write a statement like this 

```typescript 
MyProtoMessage.deserialize(new Uint8Array()) 
```
This statement will return an instance of MyProtoMessage that populated with the data you have passed in. 

I hope this is clear for you. 

Also, since the all proto messages has an deserialize method, you can write an helper function to construct as you wish.

**Comment by chenxyzl** [comment]
let a = new SearchRequest();
    a.result_per_page = "1111111"
    // a.page_number = 1111111
    console.log(a);
    let b = SearchRequest.deserializeBinary(a.serializeBinary());
    console.log(b);

**Comment by thesayyn** [comment]
@GeTOUO Do you still have any questions in your mind?

**Comment by thesayyn** [comment]
I'm going to close this issue as resolved. Please feel free to reopen.
