### ISSUE TITLE
Consider aligning API w/ Bazel proto idioms

### ISSUE THREAD

**Issue by perezd** [thesayyn/protoc-gen-ts#6]
Hey there, I was reviewing [this example](https://github.com/thesayyn/protoc-gen-ts/blob/master/examples/bazel/src/BUILD.bazel#L22) and I notice your example could be more idiomatic with existing Bazel proto rules.

1) `<lang>_proto_library` should prefer to use `deps`on a `proto_library` vs referring to it as a `src`. Example can be found here: https://docs.bazel.build/versions/master/be/java.html#java_proto_library. The rationale being this is generating source code from a collection of dependencies and is usually expressed that way.

2) `ts_library` targets that wish to use the generated ts lang proto library should express dependency on the target using `deps` instead of `src`. It's considered generally a best practice to declare a label in `srcs` that is directly are directly consumed by the rule that output source files ([citation](https://docs.bazel.build/versions/2.0.0/build-ref.html#types_of_dependencies)). In this particular case, I believe the `ts_library` is depending on a previously generated target and wouldn't be expected to list it as a src of the library itself. Additionally, its considered a best practice to not have the same file listed in `srcs` of multiple targets, which this would cause.

**Comment by thesayyn** [comment]
Hey, I agree with the first one that says <lang>_proto_library should definitely pick up the descriptors from "deps" attribute instead of "srcs". 

Since <lang>_proto_library  is a source generating target, we should not think it as a JS-producing target and also I'm not sure if ts_library picks up source files from the "deps" attribute. (I guess I'm gonna see if it works that way.)

**Comment by thesayyn** [comment]
Fixed in 0.0.7
