### ISSUE TITLE
Generated TS is invalid if proto has a message type `Map` and other messages that use the built in `map` type

### ISSUE THREAD

**Issue by KiaFarhang** [thesayyn/protoc-gen-ts#88]
Hi there,

Thanks for the library! I'd love to use it but I'm running into an issue that would be a stopper for our team. We have a proto file like this:

```
message Map {
    string key = 1;
    string value = 2;
}

message Foo {
    map<string, string> fields = 1;
}
```

When this library generates a TS file from it, the generated code fails TS compilation. The code the library spits out doesn't distinguish between its usage of the user-defined `Map` and the `Map` generic built into TypeScript.

I have [an example repo](https://github.com/KiaFarhang/ts-proto-map-example) that shows the issue.

I don't know the TS compiler API at all, but I'm curious if you think fixing this would be an easy or small task? I might be able to fix it with some guidance 😄 

Again, thanks for the library and for your time!

**Comment by thesayyn** [comment]
Hey. 
Thank you for the appreciation.

This is an issue that you would get with using the reserved keywords or globals. Like if you name your message as `Buffer` then it is going to conflict with the global `Buffer` type. So I would suggest using generic names like map or any other names that might be reserved in javascript. 

Also, I don't see any reason why one would name their message Map because it's not descriptive enough.

Maybe we could get the compiler to yell at you if you try to use reserved keywords and that's pretty much what you get in other plugins.

**Comment by thesayyn** [comment]
Even if we do `globalThis.Map` to access to map class, you are most likely to have name conflicts in other places and will be forced to import the class with an `import as` expression.
