### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by enyo** [thesayyn/protoc-gen-ts#97]
In the readme it says that there is partial web support. What does this mean exactly? Can I use this library in a browser client? Thanks!

**Comment by cortopy** [comment]
For one, I've just tried to use `@improbable-eng/grpc-web` instead of `@grpc/grpc-js` in the output ts files. The exports don't match and so it requires a lot of modifications by hand

**Comment by enyo** [comment]
@cortopy I'm using [protobuf-ts](https://github.com/timostamm/protobuf-ts) now and it works perfectly. So if that is an option for you I recommend looking into it.

**Comment by cortopy** [comment]
@enyo thanks so much!! it looks pretty good

**Comment by enyo** [comment]
@cortopy glad I could help! No disrespect to the `protoc-gen-ts` maintainers (who also did a great job), but I was so happy when I found `protobuf-ts`, a clean typescript first compiler with all features I need already implemented (for example interceptors). Have been using it for about 2 weeks now and all worked perfectly.

**Comment by thesayyn** [comment]
> In the readme it says that there is partial web support. What does this mean exactly? Can I use this library in a browser client? Thanks!

Hey.

Let me clarify what I mean by "partial".  Right now all the generated message classes (anything that is `message` or `enum`) can be used within the browser.


However, in order to support `grpc-web` the generated service client classes `{ServiceName}Client` are meant to be used in a node environment. What is missing right now is the grpc-web counterpart of `{ServiceName}Client` classes.

Soon we are going to introduce a new option called `target` which can be either `node` or `browser`, and we will generate the client classes accordingly.

**Comment by thesayyn** [comment]
#102 is there to support grpc-web directly.
